# 查询当前登录用户信息
GET http://localhost:8000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NzM4MzQyODgsImlhdCI6MTc3MzgzMjQ4OH0.SvMlabNdgfZpUViMi9FfhqKJ78fmy2P6Xrw2QUk4ztE
