"""创建knowledge_bases、documents、segments表

Revision ID: 5c1b6df00e83
Revises: aaef35a014e7
Create Date: 2026-03-20 11:32:33.005952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1b6df00e83'
down_revision: Union[str, Sequence[str], None] = 'aaef35a014e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: ready/indexing/error/empty'),
    sa.Column('document_count', sa.Integer(), nullable=False, comment='文档数量'),
    sa.Column('segment_count', sa.Integer(), nullable=False, comment='分段数量'),
    sa.Column('embedding_model', sa.String(length=100), nullable=False, comment='向量化模型'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Prompt 名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表，JSON 数组'),
    sa.Column('content', sa.Text(), nullable=False, comment='Prompt 正文内容'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='变量定义，JSON 数组'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='当前版本号'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: draft/published'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False, comment='所属知识库ID'),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment='文件名'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型: pdf/docx/md/txt/html/csv'),
    sa.Column('file_size', sa.String(length=50), nullable=True, comment='文件大小'),
    sa.Column('file_path', sa.String(length=1000), nullable=True, comment='MinIO 存储路径'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='处理状态: pending/processing/completed/failed'),
    sa.Column('segment_count', sa.Integer(), nullable=False, comment='分段数量'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True, comment='上传者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('prompt_id', sa.BigInteger(), nullable=False, comment='所属 Prompt ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='该版本的内容快照'),
    sa.Column('changelog', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为当前版本'),
    sa.Column('published_by', sa.String(length=100), nullable=True, comment='发布者'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False, comment='所属知识库ID'),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='所属文档ID'),
    sa.Column('position', sa.Integer(), nullable=False, comment='在文档中的位置序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='分段内容'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Token 数'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='关键词列表'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='检索命中次数'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('prompt_versions')
    op.drop_table('documents')
    op.drop_table('prompts')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
