"""创建agents和agent_versions表

Revision ID: cd4754f0e4da
Revises: 5c1b6df00e83
Create Date: 2026-03-20 11:41:46.378295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4754f0e4da'
down_revision: Union[str, Sequence[str], None] = '5c1b6df00e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('name', sa.String(length=200), nullable=False, comment='工具名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='工具类型: builtin/http_api/custom_function'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: enabled/disabled/error'),
    sa.Column('config', sa.JSON(), nullable=True, comment='工具配置（因类型而异）'),
    sa.Column('function_definition', sa.JSON(), nullable=True, comment='Function Calling 定义（OpenAI 格式）'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近7天调用次数'),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='成功率 %'),
    sa.Column('avg_latency', sa.Integer(), nullable=False, comment='平均延迟 ms'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agents',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Agent 名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='类型: conversation/tool/analysis/creative/workflow'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: active/inactive/error/draft'),
    sa.Column('model_id', sa.BigInteger(), nullable=True, comment='关联的模型ID'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Agent 完整配置'),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='成功率 %'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近7天调用次数'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='当前版本号'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_versions',
    sa.Column('agent_id', sa.BigInteger(), nullable=False, comment='所属 Agent ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('config', sa.JSON(), nullable=True, comment='该版本的配置快照'),
    sa.Column('changelog', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为当前版本'),
    sa.Column('published_by', sa.String(length=100), nullable=True, comment='发布者'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_versions')
    op.drop_table('agents')
    op.drop_table('tools')
    # ### end Alembic commands ###
